name: variant-calling
channels:
  - conda-forge
  - bioconda
  - defaults

dependencies:
  - python=3.10
  - r-base=4.3
  - picard=3.4.0
  - bwa=0.7.19
  - samtools=1.21
  - picard=3.2.0
  - bcftools=1.21
  - vcftools=0.1.17
  - htslib=1.21
  - tabix=1.11
  - bedtools=2.31.1
  - parallel=20240722
  - pyyaml
